<?php
/*
    $cuisToId = array("American"=>"tradamerican,newamerican", "Desserts & Ice Cream"=>"bakeries,desserts,icecream", "Breakfast & Brunch"=>"breakfast_brunch",
                        "Burgers"=>,"burgers",
                        "Cafes"=>"cafes,coffee,tea",
                        "Chinese"=>"chinese,dimsum",
                        "Delis & Sandwiches"=>"delis,sandwiches",
                        "Diners"=>"diners",
                        "French"=>"french",
                        "Greek"=>"greek",
                        "Indian & Pakistani"=>"indpak,pakistan",
                        "Italian"=>"italian",
                        "Japanese"=>"japanese,sushi",
                        "Latin American"=>"latin,peruvian",
                        "Mexican"=>"mexican",
                        "Middle Eastern"=>"mideastern",
                        "Pizza"=>"pizza",
                        "Seafood"=>"seafood",
                        "Southern & Soul Food"=>,
                        "South-East Asian"=>"thai,malaysian,singaporean,vietnamese,indonesian",
                        "Vegan & Vegetarian"=>"vegan,vegetarian");
    $idToCuis = array("tradamerican,newamerican"=>"American", 
    "bakeries,desserts,icecream"=>"Desserts & Ice Cream",
    "breakfast_brunch"=>"Breakfast & Brunch",
    "burgers"=>"Burgers",
    "cafes,coffee,tea"=>"Cafes",
    "chinese,dimsum"=>"Chinese",
    "delis,sandwiches"=>"Delis & Sandwiches",
    "diners"=>"Diners",
    "french"=>"French",
    "greek"=>"Greek",
    "indpak,pakistan"=>"Indian & Pakistani",
    "italian"=>"Italian",
                        "japanese,sushi"=>"Japanese",
                        "latin,peruvian"=>"Latin American",
                        "mexican"=>"Mexican",
                        "mideastern"=>"Middle Eastern",
                        "pizza"=>"Pizza",
                        "seafood"=>"Seafood",
                        "soulfood,southern"=>"Southern & Soul Food",
                        "thai,malaysian,singaporean,vietnamese,indonesian"=>"South-East Asian",
                        "vegan,vegetarian"=>"Vegan & Vegetarian");
                        
*/
    $idToCuis = array("tradamerican,newamerican"=>"American", 
    "bakeries,desserts,icecream"=>"Desserts & Ice Cream",
    "breakfast_brunch"=>"Breakfast & Brunch",
    "burgers"=>"Burgers",
    "cafes,coffee,tea"=>"Cafes",
    "chinese,dimsum"=>"Chinese",
    "delis,sandwiches"=>"Delis & Sandwiches",
    "diners"=>"Diners",
    "french"=>"French",
    "greek"=>"Greek",
    "indpak,pakistan"=>"Indian & Pakistani",
    "italian"=>"Italian");
     print_r($idToCuis);

?>